# Permission constants for Integration module

VIEW_INTEGRATIONS = "VIEW_INTEGRATIONS"
MANAGE_INTEGRATIONS = "MANAGE_INTEGRATIONS"
MANAGE_CREDENTIALS = "MANAGE_CREDENTIALS"
EXECUTE_INTEGRATION = "EXECUTE_INTEGRATION"
TEST_INTEGRATION = "TEST_INTEGRATION"
VIEW_INTEGRATION_LOGS = "VIEW_INTEGRATION_LOGS"

ALL_INTEGRATION_PERMISSIONS = {
    VIEW_INTEGRATIONS,
    MANAGE_INTEGRATIONS,
    MANAGE_CREDENTIALS,
    EXECUTE_INTEGRATION,
    TEST_INTEGRATION,
    VIEW_INTEGRATION_LOGS,
}
