# Permission constants for Integration module

VIEW_INTEGRATIONS = "VIEW_INTEGRATIONS"
MANAGE_INTEGRATIONS = "MANAGE_INTEGRATIONS"
MANAGE_CREDENTIALS = "MANAGE_CREDENTIALS"
EXECUTE_INTEGRATION = "EXECUTE_INTEGRATION"
TEST_INTEGRATION = "TEST_INTEGRATION"
VIEW_INTEGRATION_LOGS = "VIEW_INTEGRATION_LOGS"

MANAGE_PAYMENTS = "MANAGE_PAYMENTS"
VIEW_PAYMENT_STATUS = "VIEW_PAYMENT_STATUS"
REQUEST_REFUND = "REQUEST_REFUND"
APPROVE_REFUND = "APPROVE_REFUND"

VIEW_WHATSAPP_CONNECTION = "VIEW_WHATSAPP_CONNECTION"
MANAGE_WHATSAPP_CONNECTION = "MANAGE_WHATSAPP_CONNECTION"
SEND_WHATSAPP_MESSAGE = "SEND_WHATSAPP_MESSAGE"
MANAGE_WHATSAPP_WEBHOOK = "MANAGE_WHATSAPP_WEBHOOK"

ALL_INTEGRATION_PERMISSIONS = {
    VIEW_INTEGRATIONS,
    MANAGE_INTEGRATIONS,
    MANAGE_CREDENTIALS,
    EXECUTE_INTEGRATION,
    TEST_INTEGRATION,
    VIEW_INTEGRATION_LOGS,
    MANAGE_PAYMENTS,
    VIEW_PAYMENT_STATUS,
    REQUEST_REFUND,
    APPROVE_REFUND,
    VIEW_WHATSAPP_CONNECTION,
    MANAGE_WHATSAPP_CONNECTION,
    SEND_WHATSAPP_MESSAGE,
    MANAGE_WHATSAPP_WEBHOOK,
}
