"""create_phase_1_5_tables

Revision ID: a0e47a600bbf
Revises: 'd1e0b5f64eb8'
Create Date: 2026-09-05 01:57:59.859323+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0e47a600bbf'
down_revision: Union[str, None] = 'd1e0b5f64eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_guardrails',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_definition', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_ai_guardrails_tenant_key')
    )
    op.create_index(op.f('ix_ai_guardrails_tenant_id'), 'ai_guardrails', ['tenant_id'], unique=False)
    op.create_table('knowledge_categories',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_knowledge_categories_tenant_key')
    )
    op.create_index(op.f('ix_knowledge_categories_tenant_id'), 'knowledge_categories', ['tenant_id'], unique=False)
    op.create_table('onboarding_checklists',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_onboarding_checklists_tenant_key')
    )
    op.create_index(op.f('ix_onboarding_checklists_tenant_id'), 'onboarding_checklists', ['tenant_id'], unique=False)
    op.create_table('provisioning_audits',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.String(length=50), nullable=True),
    sa.Column('new_state', sa.String(length=50), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisioning_audits_tenant_id'), 'provisioning_audits', ['tenant_id'], unique=False)
    op.create_table('workflow_configurations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_workflow_configurations_tenant_key')
    )
    op.create_index(op.f('ix_workflow_configurations_tenant_id'), 'workflow_configurations', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('lifecycle_state', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('previous_state', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('state_transition_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('transition_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'transition_reason')
    op.drop_column('tenants', 'state_transition_at')
    op.drop_column('tenants', 'previous_state')
    op.drop_column('tenants', 'lifecycle_state')
    op.drop_index(op.f('ix_workflow_configurations_tenant_id'), table_name='workflow_configurations')
    op.drop_table('workflow_configurations')
    op.drop_index(op.f('ix_provisioning_audits_tenant_id'), table_name='provisioning_audits')
    op.drop_table('provisioning_audits')
    op.drop_index(op.f('ix_onboarding_checklists_tenant_id'), table_name='onboarding_checklists')
    op.drop_table('onboarding_checklists')
    op.drop_index(op.f('ix_knowledge_categories_tenant_id'), table_name='knowledge_categories')
    op.drop_table('knowledge_categories')
    op.drop_index(op.f('ix_ai_guardrails_tenant_id'), table_name='ai_guardrails')
    op.drop_table('ai_guardrails')
    # ### end Alembic commands ###
