"""add_phase6_integrations

Revision ID: 5066dcbc0b43
Revises: '72dbe1a9c9ce'
Create Date: 2026-09-05 08:57:23.510518+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5066dcbc0b43'
down_revision: Union[str, None] = '72dbe1a9c9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
